import { defineTable } from 'convex/server';
import { v } from 'convex/values';
import { playerId } from './aiTown/ids';
const project = v.union(v.literal('hospital'), v.literal('market'), v.literal('bridge'));
export const civicTables = {
 civicWork:defineTable({worldId:v.id('worlds'),playerId:v.string(),day:v.number(),item:v.string(),quantity:v.number()}).index('workerDay',['worldId','playerId','day']),
  civicSeasons: defineTable({worldId:v.id('worlds'),version:v.number(),startedDay:v.number(),lastDay:v.number(),lastFestivalDay:v.number()}).index('worldId',['worldId']),
  civicProjects: defineTable({worldId:v.id('worlds'),key:project,title:v.string(),description:v.string(),cost:v.number(),materialGoal:v.number(),laborGoal:v.number(),funds:v.number(),spent:v.number(),materials:v.number(),labor:v.number(),status:v.union(v.literal('proposed'),v.literal('building'),v.literal('completed')),startedDay:v.number(),completedDay:v.optional(v.number()),votes:v.array(v.object({playerId,support:v.boolean(),reason:v.string(),explicit:v.boolean()})),contributions:v.array(v.object({playerId,day:v.number(),coins:v.number(),labor:v.number()}))}).index('worldId',['worldId']),
  civicCommitments: defineTable({worldId:v.id('worlds'),kind:v.union(v.literal('loan'),v.literal('delivery'),v.literal('campaign')),from:playerId,to:v.optional(playerId),projectKey:v.optional(project),amount:v.number(),paid:v.number(),status:v.union(v.literal('offered'),v.literal('active'),v.literal('fulfilled'),v.literal('broken'),v.literal('cancelled')),createdDay:v.number(),dueDay:v.number(),title:v.string(),outcome:v.optional(v.string())}).index('worldId',['worldId']),
  civicNotices: defineTable({worldId:v.id('worlds'),day:v.number(),kind:v.string(),title:v.string(),body:v.string(),public:v.boolean(),participants:v.array(playerId)}).index('worldId',['worldId']),
  civicKnowledge: defineTable({worldId:v.id('worlds'),owner:playerId,noticeId:v.id('civicNotices'),account:v.string(),source:v.string(),confidence:v.number(),hops:v.number(),day:v.number()}).index('owner',['worldId','owner']).index('fact',['worldId','owner','noticeId']),
  civicElections: defineTable({worldId:v.id('worlds'),startedDay:v.number(),votingDay:v.number(),endsDay:v.number(),status:v.union(v.literal('campaigning'),v.literal('voting'),v.literal('completed')),candidates:v.array(v.object({playerId,projectKey:project,pledge:v.string()})),ballots:v.array(v.object({voterId:playerId,candidateId:playerId,reason:v.string(),explicit:v.boolean()})),winnerId:v.optional(playerId)}).index('worldId',['worldId']),
  civicRequests: defineTable({worldId:v.id('worlds'),kind:v.union(v.literal('project'),v.literal('mediation'),v.literal('festival')),title:v.string(),body:v.string(),from:playerId,other:v.optional(playerId),projectKey:v.optional(project),createdDay:v.number(),expiresDay:v.number(),status:v.union(v.literal('open'),v.literal('accepted'),v.literal('declined'),v.literal('completed'),v.literal('expired')),outcome:v.optional(v.string())}).index('worldId',['worldId']),
};
