import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1100,height:850}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning')console.log(m.text().slice(0,200))});
await page.goto(process.env.TOWN_URL||'http://127.0.0.1:5183');await page.waitForFunction(()=>window.__townReady,null,{timeout:90000});await page.getByRole('button',{name:'暂停居民活动',exact:true}).click();
for(let i=0;i<8;i++){await page.evaluate(i=>{const t=window.__town,p=t.people[i];t.life.setState(p,'idle');p.mixer.update(.5);t.life.align(p);t.select(i,true)},i);await page.screenshot({path:`cast-${i}.png`})}
const motionAudit=await page.evaluate(()=>{const t=window.__town;let tPoses=0;for(const p of t.people){t.life.setState(p,'walk');p.transition=null;const joints={};p.visual.traverse(b=>{if(b.isBone)joints[b.name]=b});const find=(side,part)=>Object.values(joints).find(b=>b.name.endsWith(part+'_'+side)||b.name===`Bip01_${side.toUpperCase()}_${part==='hand'?'Hand':'UpperArm'}`||b.name===`Bip01 ${side.toUpperCase()} ${part==='hand'?'Hand':'UpperArm'}`);for(let i=0;i<160;i++){p.mixer.update(.05);p.group.updateMatrixWorld(true);let raised=0;for(const side of ['l','r']){const hand=find(side,'hand'),arm=find(side,'upperarm');if(!hand||!arm)throw Error('Missing arm audit bones: '+p.assetId);if(hand.getWorldPosition(p.group.position.clone()).y>arm.getWorldPosition(p.group.position.clone()).y-.15)raised++}if(raised===2)tPoses++}t.life.align(p)}return {tPoses,geometry:t.measure()}});console.log(JSON.stringify({motionAudit}));assert.equal(motionAudit.tPoses,0);assert.ok(motionAudit.geometry.every(p=>p.size[1]>1.3&&p.size[1]<2.1));
await page.evaluate(()=>window.__town.select(5,true));await page.screenshot({path:'cast-walking.png'});
const result=await page.evaluate(()=>{const t=window.__town,initial=JSON.stringify(t.data.residents),states=new Set();let hits=0;for(let i=0;i<900;i++){t.life.step(.05);for(const p of t.people){states.add(p.state);if(!t.life.clearWorld(p.group.position.x,p.group.position.z))hits++}}return {cast:t.people.map(p=>({name:p.resident.name,asset:p.assetId,feet:p.feet.reduce((n,[m,v])=>n+v.length,0)})),hits,states:[...states],grounding:t.life.groundingReport(),unchanged:initial===JSON.stringify(t.data.residents)}});
console.log(JSON.stringify({...result,errors}));assert.equal(new Set(result.cast.map(p=>p.asset)).size,8);assert.equal(result.hits,0);assert.ok(result.cast.every(p=>p.feet>0));assert.deepEqual(errors,[]);await browser.close();
