import * as T from 'three';
import {connectCivic} from './civic-ui.js';
export async function backend(kind,path,args={}){const response=await fetch('/api/backend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,path,args})});const data=await response.json();if(!response.ok||data.status!=='success')throw Error(data.errorMessage??'后端连接失败');return data.value}
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function connectWorld(town){
 let world,engine,status,overview,conversation,selectedId,alive=true,busy=false,lastOverview=0,error='',joining=false;
 const human=()=>world?.players.find(p=>p.human);
 const marker=new T.Mesh(new T.RingGeometry(.35,.48,32),new T.MeshBasicMaterial({color:'#368ded',side:T.DoubleSide}));marker.rotation.x=-Math.PI/2;marker.visible=false;town.scene.add(marker);
 const panel=document.createElement('section');panel.id='live-panel';panel.innerHTML=`<div class="live-heading"><b>原世界 · 实时连接</b><span id="connection">连接中…</span></div><div class="live-controls"><button id="join-world">进入小镇</button><button id="talk-resident">与选中居民交谈</button><button id="accept-talk">接受邀请</button><button id="leave-talk">结束对话</button><button id="freeze-world">暂停原世界</button><button id="show-observatory">观察站</button></div><p id="live-hint">正在连接 PCUbuntu 的原数据库…</p><div id="live-messages"></div><form id="chat-form"><input id="chat-text" maxlength="2000" placeholder="进入小镇并建立对话后发送中文消息" autocomplete="off"><button id="send-chat">发送</button></form>`;document.body.append(panel);
 const dialog=document.createElement('dialog');dialog.id='live-observatory';dialog.innerHTML='<button id="close-observatory">关闭</button><h2>实时观察站</h2><div id="observatory-content"></div>';document.body.append(dialog);
 const $=id=>document.getElementById(id),report=e=>{$('live-hint').textContent=e.message};
 async function input(name,args){const inputId=await backend('mutation','world:sendWorldInput',{engineId:engine._id,name,args});for(let i=0;i<50;i++){const result=await backend('query','aiTown/main:inputStatus',{inputId});if(result){if(result.kind==='error')throw Error(result.message);return result.value}await new Promise(r=>setTimeout(r,200))}throw Error('世界尚未处理操作，请稍后查看，勿重复发送')}
 async function refresh(){if(busy)return;busy=true;try{
  status=await backend('query','world:defaultWorldStatus');if(!status)throw Error('未找到原世界，不会自动建档');
  if(status.worldId!==town.data.provenance.worldId)throw Error('后端世界 ID 与存档不一致，已拒绝连接');
  const state=await backend('query','world:worldState',{worldId:status.worldId});world=state.world;engine=state.engine;error='';
  town.life.setLiveWorld(world,status.status==='running'&&engine.running);
  $('connection').textContent=status.status==='running'?'AI 世界运行中':'原世界已暂停';document.querySelector('.state').textContent='原世界实时数据 · JanUbuntu 模型';
  $('freeze-world').textContent=status.status==='running'?'暂停原世界':'继续原世界';$('join-world').textContent=human()?'离开小镇':'进入小镇';
  const chosen=town.people.find(p=>p.resident.playerId===$('resident-select').value);selectedId=chosen?.resident.playerId;
  const player=human();marker.visible=Boolean(player);if(player){const [x,z]=town.terrain.xy(player.position.x,player.position.y);marker.position.set(x,town.terrain.surfaceHeight(player.position.x,player.position.y)+.04,z)}conversation=world.conversations.find(c=>c.participants.some(p=>p.playerId===(player?.id??selectedId)));
  $('live-hint').textContent=player?`你已进入原世界。点击地面可移动；选中居民后发起交谈。`:'正在观看原世界真实行为，点击进入小镇即可对话。';
  const member=conversation?.participants.find(p=>p.playerId===player?.id),canSend=member?.status.kind==='participating';$('send-chat').disabled=!canSend;$('chat-text').disabled=!canSend;$('accept-talk').disabled=!player||!conversation||member?.status.kind!=='invited';
  $('talk-resident').disabled=!player||!chosen?.group.visible||Boolean(conversation);$('leave-talk').disabled=!player||!conversation;
  if(conversation){const messages=await backend('query','messages:listMessages',{worldId:world._id,conversationId:conversation.id});$('live-messages').innerHTML=messages.slice(-12).map(m=>`<p><b>${escape(m.authorName)}</b>：${escape(m.text)}</p>`).join('')||'<p>正在靠近对方或等待回复…</p>'}else $('live-messages').innerHTML='<p>选中正在交谈的居民，可旁观对话。</p>';
  if(Date.now()-lastOverview>12000){overview=await backend('query','observatory:overview',{worldId:world._id});lastOverview=Date.now();applyOverview()}
  $('notice').textContent=`原世界第 ${overview?.society?.simulatedDay??town.data.provenance.day} 天 · 引擎代数 ${engine.generationNumber} · 数据由 PCUbuntu 持续保存`;
 }catch(e){error=e.message;town.life.pauseLive();$('connection').textContent='后端离线 · 已停止展示推进';document.querySelector('.state').textContent='连接中断 · 不以本地活动冒充 AI';report(e)}finally{busy=false}}
 function applyOverview(){if(!overview)return;for(const p of town.people){const record=overview.society?.residents.find(r=>r.playerId===p.resident.playerId),memory=overview.residents.find(r=>r.playerId===p.resident.playerId);if(record){Object.assign(p.resident,record);p.resident.partnerId=town.people.find(q=>q.resident.name===record.partnerName)?.resident.playerId;p.group.visible=record.alive;p.tag.visible=record.alive&&!document.body.classList.contains('portrait')}if(memory){p.resident.memories.count=memory.memoryCount;p.resident.memories.reflections=memory.reflectionCount}}
  town.refreshProfile();const s=overview.society; $('statistics').innerHTML=`<div><b>${s?.simulatedDay??'—'}</b><span>世界日</span></div><div><b>${overview.totals.residents}</b><span>在世居民</span></div><div><b>${overview.totals.memories}</b><span>长期记忆</span></div>`;
  $('observatory-content').innerHTML=`<p>对话 ${overview.totals.conversations} · 消息 ${overview.totals.messages} · 记忆 ${overview.totals.memories} · 反思 ${overview.totals.reflections}</p><p>镇长 ${escape(s?.mayorName)} · 财政 ${s?.treasury??0}</p><h3>居民与健康</h3>${(s?.residents??[]).map(r=>`<p>${escape(r.name)} · ${escape(r.faction)} · ${r.alive?'在世':'已故'} · 血量 ${r.health} · 金币 ${r.coins} · 伴侣 ${escape(r.partnerName??'无')}</p>`).join('')}<h3>最近事件</h3>${(s?.events??[]).map(e=>`<p><b>第 ${e.simulatedDay} 天 · ${escape(e.title)}</b><br>${escape(e.description)}</p>`).join('')}<h3>社会关系</h3>${(s?.relationships??[]).map(r=>`<p>${escape(r.names.join(' / '))} · ${escape(r.stage)} · 信任 ${r.trust} · 冲突 ${r.conflict}</p>`).join('')}<h3>法律</h3>${(s?.laws??[]).map(r=>`<p>${escape(r.title)}：${escape(r.description)}</p>`).join('')}<h3>最近记忆</h3>${overview.recentChronicle.map(m=>`<p>${escape(m.residentName)}：${escape(m.description)}</p>`).join('')}`;
 }
 const action=(id,fn)=>$(id).onclick=async()=>{try{$(id).disabled=true;await fn();await refresh()}catch(e){report(e)}finally{$(id).disabled=false}};
 action('join-world',async()=>{if(joining)return;joining=true;try{await backend('mutation',human()?'world:leaveWorld':'world:joinWorld',{worldId:world._id})}finally{joining=false}});
 action('talk-resident',()=>input('startConversation',{playerId:human().id,invitee:selectedId}));action('accept-talk',()=>input('acceptInvite',{playerId:human().id,conversationId:conversation.id}));action('leave-talk',()=>input('leaveConversation',{playerId:human().id,conversationId:conversation.id}));action('freeze-world',()=>backend('mutation',status.status==='running'?'testing:stop':'testing:resume'));
 $('show-observatory').onclick=()=>dialog.showModal();$('close-observatory').onclick=()=>dialog.close();
 let sending=false;const send=async()=>{if(sending)return;const text=$('chat-text').value.trim();if(!text||!human()||!conversation)return;sending=true;$('send-chat').disabled=true;try{const bytes=crypto.getRandomValues(new Uint8Array(16));const messageUuid=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');await backend('mutation','messages:writeMessage',{worldId:world._id,conversationId:conversation.id,playerId:human().id,messageUuid,text});$('chat-text').value='';await refresh()}catch(e){report(e)}finally{sending=false;$('send-chat').disabled=false}};
 $('chat-form').onsubmit=e=>{e.preventDefault();void send()};$('chat-text').onkeydown=e=>{e.stopPropagation();if(e.isComposing||e.keyCode===229){if(e.key==='Enter')e.preventDefault()}};
 const civic=connectCivic(town,backend);town.civic=civic;
 const timer=setInterval(refresh,1800);void refresh();return {get world(){return world},get overview(){return overview},get error(){return error},refresh,move:async destination=>{if(human())try{await input('moveTo',{playerId:human().id,destination})}catch(e){report(e)}},dispose(){alive=false;clearInterval(timer);civic.dispose()}};
}
