import * as T from 'three';
import {addEnvironmentAssets} from './environment-assets.js';

export async function buildTerrain(scene,map,renderer){
 const S=map.metersPerTile,W=map.width,H=map.height,R=map.resolution,FW=W*R,FH=H*R;
 const xy=(x,y)=>[(x-W/2)*S,(y-H/2)*S];
 const field=(x,y)=>map.fields[Math.max(0,Math.min(FH-1,Math.floor(y*R)))*FW+Math.max(0,Math.min(FW-1,Math.floor(x*R)))];
 const highland=y=>Math.max(0,Math.min(1,(12-y)/3))*1.5;
 function height(x,y){let h=.12+highland(y);if(field(x,y)===1)h-=.7;const cliff=(x<6&&y>38&&y<44)||(x>10&&x<19&&y>37&&y<43);if(cliff)h+=1.8;return h;}
 const loader=new T.TextureLoader(),materials=new Map();
 function basic(c){if(!materials.has(c))materials.set(c,new T.MeshStandardMaterial({color:c,roughness:.87}));return materials.get(c)}
 function pbr(name,color,repeat=1){const m=new T.MeshStandardMaterial({color,roughness:.94});for(const [part,key]of[['color','map'],['normal','normalMap']])loader.load(`/assets/${name}-${part}.jpg`,t=>{t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(repeat,repeat);t.anisotropy=8;if(key==='map')t.colorSpace=T.SRGBColorSpace;m[key]=t;m.normalScale.set(.6,.6);m.needsUpdate=true});return m}
 const grass=new T.MeshStandardMaterial({color:'#9a9d89',roughness:1,vertexColors:true}),dirt=pbr('mud','#bfb29a'),bark=pbr('bark','#8d816c'),stone=pbr('bricks','#a6a095');
 loader.load('/assets/grass.jpg',t=>{t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;t.anisotropy=8;grass.map=t;grass.needsUpdate=true});
 const chunks=[[],[],[]],uvs=[[],[],[]];
 const terrainGeo=new T.PlaneGeometry(W*S,H*S,FW,FH);terrainGeo.rotateX(-Math.PI/2);const pos=terrainGeo.attributes.position;
 for(let i=0;i<pos.count;i++){const x=pos.getX(i)/S+W/2,y=pos.getZ(i)/S+H/2;pos.setY(i,height(x,y))}terrainGeo.computeVertexNormals();terrainGeo.attributes.uv.array.forEach((_,i,a)=>a[i]*=i%2?H/3:W/3);
 const colors=[];for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),variation=.85+.1*Math.sin(x*.39)*Math.cos(z*.27)+.04*Math.sin(x*1.7+z*.6);colors.push(variation,variation,variation*.96)}terrainGeo.setAttribute('color',new T.Float32BufferAttribute(colors,3));
 grass.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\n diffuseColor.rgb=mix(diffuseColor.rgb,vec3(dot(diffuseColor.rgb,vec3(.299,.587,.114))),.22);')};
 const ground=new T.Mesh(terrainGeo,grass);ground.receiveShadow=true;scene.add(ground);
 function quad(out,uv,x,y,h){const x0=(x/R-W/2)*S,x1=x0+S/R,z0=(y/R-H/2)*S,z1=z0+S/R;const h0=typeof h==='function'?h(z0):h,h1=typeof h==='function'?h(z1):h;out.push(x0,h0,z0,x0,h1,z1,x1,h1,z1,x0,h0,z0,x1,h1,z1,x1,h0,z0);uv.push(x0/3,z0/3,x0/3,z1/3,x1/3,z1/3,x0/3,z0/3,x1/3,z1/3,x1/3,z0/3)}
 for(let y=0;y<FH;y++)for(let x=0;x<FW;x++){const type=map.fields[y*FW+x];if(type===1)quad(chunks[1],uvs[1],x,y,z=>-.22+highland(z/S+H/2));if(type===2)quad(chunks[2],uvs[2],x,y,height((x+.5)/R,(y+.5)/R)+.025)}
 function meshOf(vertices,uv,material){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.computeVertexNormals();const m=new T.Mesh(g,material);m.receiveShadow=true;scene.add(m);return m}
 const waterMat=new T.MeshPhysicalMaterial({color:'#35695e',roughness:.22,metalness:.24,transparent:true,opacity:.89,clearcoat:1,clearcoatRoughness:.18});
 loader.load('/assets/mud-normal.jpg',t=>{t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(2,2);waterMat.normalMap=t;waterMat.normalScale.set(.18,.18);waterMat.needsUpdate=true});
 waterMat.onBeforeCompile=shader=>{shader.uniforms.time={value:0};shader.vertexShader='uniform float time;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.y += sin(position.x*3.0+time)*cos(position.z*2.0-time*.7)*.018;');waterMat.userData.shader=shader};
 meshOf(chunks[1],uvs[1],waterMat);meshOf(chunks[2],uvs[2],dirt);
 function box(w,h,d,material,x,y,z,parent=scene){const m=new T.Mesh(new T.BoxGeometry(w,h,d),typeof material==='string'?basic(material):material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 function cyl(rt,rb,h,material,x,y,z,parent=scene){const m=new T.Mesh(new T.CylinderGeometry(rt,rb,h,12),typeof material==='string'?basic(material):material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 const trunkMatrices=[],leafMatrices=[],leafColors=[];let seed=1905;const rand=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};const dummy=new T.Object3D();
 function tree(tx,ty,scale=1){const[x,z]=xy(tx,ty),y=height(tx,ty);dummy.position.set(x,y+2.3*scale,z);dummy.rotation.set(0,0,0);dummy.scale.set(.23*scale,4.6*scale,.23*scale);dummy.updateMatrix();trunkMatrices.push(dummy.matrix.clone());for(let i=0;i<3;i++){dummy.position.set(x+Math.sin(i*2)*.45*scale,y+(3.3+i*.3)*scale,z+Math.cos(i*2)*.45*scale);dummy.rotation.set(Math.cos(i*2)*.5,0,Math.sin(i*2)*.5);dummy.scale.set(.08*scale,2.2*scale,.08*scale);dummy.updateMatrix();trunkMatrices.push(dummy.matrix.clone())}for(let i=0;i<380;i++){const a=rand()*Math.PI*2,r=Math.sqrt(rand())*1.6*scale;dummy.position.set(x+Math.sin(a)*r,y+(4.4+(rand()-.5)*2)*scale,z+Math.cos(a)*r);dummy.rotation.set(rand()*Math.PI,rand()*6.28,rand()*6.28);dummy.scale.setScalar((.2+rand()*.18)*scale);dummy.updateMatrix();leafMatrices.push(dummy.matrix.clone());leafColors.push(new T.Color().setHSL(.23+rand()*.055,.3+rand()*.25,.23+rand()*.17))}}
 for(let y=0;y<H;y+=2)for(let x=0;x<W;x+=2){let count=0;for(let dy=0;dy<2;dy++)for(let dx=0;dx<2;dx++)count+=map.forest[(y+dy)*W+x+dx]??0;if(count>=2)tree(x+.7,y+.7,.9+rand()*.25)}
 const markers=[],rotors=[],flames=[];
 function rock(tx,ty,size=1){const[x,z]=xy(tx,ty);const m=new T.Mesh(new T.DodecahedronGeometry(size,1),basic('#8d8b76'));m.scale.set(1,.7,.8);m.position.set(x,height(tx,ty)+size*.4,z);m.rotation.set(rand(),rand()*6,rand());m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
 for(let y=0;y<FH;y+=3)for(let x=0;x<FW;x+=3){if(map.fields[y*FW+x]===1&&(field((x+3)/R,y/R)!==1||field(x/R,(y+3)/R)!==1))rock((x+.4)/R,(y+.4)/R,.13+rand()*.22)}
 for(const prop of map.props){const[x,z]=xy(prop.x,prop.y),y=height(prop.x,prop.y);let object;
  if(['largeTree','sapling','pine'].includes(prop.type)){tree(prop.x,prop.y,prop.type==='largeTree'?1.3:.55);continue}
  if(prop.type==='tent'){const g=new T.Group();g.position.set(x,y,z);scene.add(g);const w=prop.width*S,d=prop.depth*S*.7,h=2.35;const shape=new T.Shape();shape.moveTo(-w/2,0);shape.lineTo(0,h);shape.lineTo(w/2,0);shape.closePath();const geo=new T.ExtrudeGeometry(shape,{depth:d,bevelEnabled:false});geo.translate(0,0,-d/2);const tent=new T.Mesh(geo,basic('#bdb192'));tent.castShadow=true;tent.receiveShadow=true;g.add(tent);const opening=new T.Shape();opening.moveTo(-.55,0);opening.lineTo(-.5,1.3);opening.lineTo(.5,1.3);opening.lineTo(.55,0);const door=new T.Mesh(new T.ShapeGeometry(opening),basic('#302d23'));door.position.z=d/2+.02;g.add(door);for(const sign of[-1,1]){const line=new T.BufferGeometry().setFromPoints([new T.Vector3(sign*w/2,1,z*0),new T.Vector3(sign*(w/2+.5),0,.6)]);g.add(new T.Line(line,new T.LineBasicMaterial({color:'#b6b6a1'})))}object=g;markers.push({label:'原营地帐篷',position:new T.Vector3(x,y+3,z),source:prop.source})}
  else if(prop.type==='windmill'){const g=new T.Group();g.position.set(x,y,z);scene.add(g);cyl(.8,1.2,5.8,stone,0,2.9,0,g);const roof=new T.Mesh(new T.ConeGeometry(1.2,1.5,12),basic('#7f6550'));roof.position.y=6.5;g.add(roof);const rotor=new T.Group();rotor.position.set(0,5.3,1);g.add(rotor);for(let i=0;i<4;i++){const blade=new T.Group();blade.rotation.z=i*Math.PI/2;rotor.add(blade);box(.13,3.9,.15,bark,0,1.9,0,blade);box(.75,2.7,.05,'#d9d3bb',.3,2.35,0,blade);for(let k=0;k<6;k++)box(.8,.04,.08,'#6b5845',.3,1.05+k*.48,.04,blade)}cyl(.17,.17,.4,'#6a5640',0,5.3,1,g).rotation.x=Math.PI/2;rotors.push(rotor);object=g;markers.push({label:'原风车',position:new T.Vector3(x,y+8,z),source:prop.source})}
  else if(prop.type==='waterfall'){const fall=new T.Mesh(new T.PlaneGeometry(S,2.1,4,10),new T.MeshStandardMaterial({color:'#b6ded8',transparent:true,opacity:.72,roughness:.15,side:T.DoubleSide}));fall.position.set(x,.6,z);fall.visible=false;scene.add(fall);object=fall;for(let i=0;i<5;i++)rock(prop.x+(rand()-.5),prop.y+1,.18)}
  else if(prop.type==='campfire'){for(let i=0;i<8;i++)rock(prop.x+Math.cos(i)*.48,prop.y+Math.sin(i)*.48,.22);const f=new T.Mesh(new T.ConeGeometry(.35,.85,9),new T.MeshBasicMaterial({color:'#ee982f',transparent:true,opacity:.85}));f.position.set(x,y+.4,z);scene.add(f);flames.push(f);markers.push({label:'原营火',position:new T.Vector3(x,y+1.7,z),source:prop.source});object=f}
  else if(prop.type==='crates'){const g=new T.Group();g.position.set(x,y,z);scene.add(g);const count=prop.width>1?3:1;for(let i=0;i<count;i++){const px=(i%2)*.65,pz=0,py=i===2?.7:0;box(.65,.65,.65,bark,px,py+.32,pz,g);for(const edge of[-.29,.29]){box(.07,.68,.72,'#615b46',px+edge,py+.32,pz,g);box(.7,.06,.7,'#615b46',px,py+.32+edge,pz,g)}}object=g}
  else if(prop.type==='barrel'){object=cyl(.3,.32,.75,bark,x,y+.38,z);for(const h of[.15,.6])cyl(.325,.325,.06,'#514f42',x,y+h,z)}
  else if(prop.type==='stump'){object=cyl(.3,.42,.5,bark,x,y+.25,z);cyl(.29,.29,.012,'#b29b72',x,y+.51,z)}
  else if(['log','logStanding'].includes(prop.type)){object=cyl(.3,.35,prop.width*S*.8,bark,x,y+.3,z);object.rotation.z=prop.type==='log'?Math.PI/2:.3;object.rotation.y=.5}
  else if(['boulder','stone'].includes(prop.type)){object=rock(prop.x,prop.y,prop.type==='boulder'?.65:.32)}
  else {const g=new T.Group();g.position.set(x,y,z);scene.add(g);for(let k=0;k<6;k++){const xx=(rand()-.5)*.7,zz=(rand()-.5)*.7;const stem=cyl(.014,.019,.3,'#5a773c',xx,.15,zz,g);const bloom=new T.Mesh(new T.SphereGeometry(.055,5,4),basic(['#d8c0e3','#e0d080','#ddacb3'][k%3]));bloom.position.set(xx,.31,zz);g.add(bloom)}object=g}
  if(object){object.userData.sourcePropId=prop.id;object.userData.source=prop.source}
 }
 const trunks=new T.InstancedMesh(new T.CylinderGeometry(.75,1,1,8),bark,trunkMatrices.length);trunkMatrices.forEach((m,i)=>trunks.setMatrixAt(i,m));trunks.castShadow=true;scene.add(trunks);
 leafMatrices.forEach(m=>m.scale(new T.Vector3(1.65,1.65,1.65)));
 const shape=new T.Shape();shape.moveTo(0,-.5);shape.quadraticCurveTo(.33,0,0,.5);shape.quadraticCurveTo(-.33,0,0,-.5);const leaves=new T.InstancedMesh(new T.ShapeGeometry(shape,3),new T.MeshStandardMaterial({color:'#a2b390',side:T.DoubleSide,roughness:.95}),leafMatrices.length);leafMatrices.forEach((m,i)=>{leaves.setMatrixAt(i,m);leaves.setColorAt(i,leafColors[i])});leaves.castShadow=true;leaves.receiveShadow=true;scene.add(leaves);
 const assetReport=await addEnvironmentAssets(scene,map,xy,height,renderer);
 trunks.visible=false;leaves.visible=false;
 const replaced=new Set(map.props.filter(p=>['stump','boulder','stone'].includes(p.type)).map(p=>p.id));scene.children.forEach(o=>{if(replaced.has(o.userData.sourcePropId))o.visible=false});
 function surfaceHeight(x,y){const gx=Math.max(0,Math.min(W*R-1e-5,x*R)),gy=Math.max(0,Math.min(H*R-1e-5,y*R)),ix=Math.floor(gx),iy=Math.floor(gy),fx=gx-ix,fy=gy-iy,a=height(ix/R,iy/R),b=height((ix+1)/R,iy/R),c=height(ix/R,(iy+1)/R),d=height((ix+1)/R,(iy+1)/R);return fx+fy<=1?a+(b-a)*fx+(c-a)*fy:d+(c-d)*(1-fx)+(b-d)*(1-fy)}
 const colliders=[];scene.updateMatrixWorld(true);for(const o of scene.children){if(!o.visible)continue;if(o.userData.navigationObstacle&&o.isInstancedMesh){o.geometry.computeBoundingBox();for(let i=0;i<o.count;i++){const m=new T.Matrix4();o.getMatrixAt(i,m);colliders.push(o.geometry.boundingBox.clone().applyMatrix4(m.premultiply(o.matrixWorld)))}}else if(o.userData.sourcePropId&&!o.userData.sourcePropId.includes('waterfall'))colliders.push(new T.Box3().setFromObject(o))}
 return{colliders,xy,height,surfaceHeight,markers,updateView:assetReport.update,lodCounts:assetReport.lodCounts,counts:{props:map.props.length,trees:assetReport.trees,realisticAssets:assetReport.assets,waterSamples:chunks[1].length/18},update(time){if(waterMat.userData.shader)waterMat.userData.shader.uniforms.time.value=time;rotors.forEach(r=>r.rotation.z=time*.12);flames.forEach(f=>f.scale.y=1+Math.sin(time*8)*.15)}};
}
