import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {clone} from 'three/addons/utils/SkeletonUtils.js';
import {Sky} from 'three/addons/objects/Sky.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import './style.css';
import './polish.css';
const $=id=>document.getElementById(id);
document.querySelector('.intro').innerHTML='<div class="eyebrow">3D ENVIRONMENT STUDY / 01</div><h1>林间街区</h1><p>光落在街道上，故事从这里开始。</p><div class="stats"><div><strong>05</strong><span>展示居民</span></div><div><strong>17:30</strong><span>黄金时刻</span></div></div>';
$('source').textContent='真人扫描 · 3D 展示 · 无 LLM';$('settings').textContent='人物近景';$('pause').textContent='暂停行走';$('night').textContent='蓝调时刻';$('events').innerHTML='<div class="event">独立展示场景<p>5 位居民，4 套真人扫描素材，包含散步、驻足、跳舞和静态姿势。</p></div><div class="event">探索视角<p>拖动旋转，滚轮靠近；点击人物查看近景。按 1 / 2 / 3 切换机位，H 隐藏界面。</p></div>';
const next=document.createElement('button');next.className='next-person';next.textContent='下一位居民';document.querySelector('nav').prepend(next);next.onclick=()=>select((selected+1)%5,true);
const scene=new T.Scene();scene.fog=new T.FogExp2('#c6d1cf',.009);
const renderer=new T.WebGLRenderer({canvas:$('world'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const camera=new T.PerspectiveCamera(43,innerWidth/innerHeight,.1,220),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=2;controls.maxDistance=75;controls.maxPolarAngle=Math.PI*.485;controls.target.set(0,1,-2);camera.position.set(17,12,23);
const hemi=new T.HemisphereLight('#d9eaff','#75644f',1.5);scene.add(hemi);const sun=new T.DirectionalLight('#ffe0ad',3.8);sun.position.set(-18,25,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-35,right:35,top:35,bottom:-35,near:.5,far:90});sun.shadow.normalBias=.025;scene.add(sun);
const sky=new Sky();sky.scale.setScalar(150);sky.material.uniforms.turbidity.value=3;sky.material.uniforms.rayleigh.value=1.5;sky.material.uniforms.sunPosition.value.copy(sun.position);scene.add(sky);
new RGBELoader().load('/assets/sunset.hdr',hdr=>{hdr.mapping=T.EquirectangularReflectionMapping;scene.environment=hdr;scene.environmentIntensity=.65});
let seed=42;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function texture(kind){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d');ctx.fillStyle=kind==='road'?'#666861':kind==='stone'?'#b4afa0':'#a68569';ctx.fillRect(0,0,512,512);for(let i=0;i<22000;i++){ctx.fillStyle=`rgba(${rand()>.5?'255,255,240':'20,20,15'},${rand()*.1})`;ctx.fillRect(rand()*512,rand()*512,2,2)}if(kind!=='road'){const h=kind==='stone'?64:32,w=kind==='stone'?128:100;ctx.strokeStyle=kind==='stone'?'#858579':'#c6b7a0';ctx.lineWidth=3;for(let y=0;y<512;y+=h){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(512,y);ctx.stroke();for(let x=-w;x<512;x+=w){ctx.beginPath();ctx.moveTo(x+(y/h%2)*w/2,y);ctx.lineTo(x+(y/h%2)*w/2,y+h);ctx.stroke()}}}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t}
const stone=texture('stone');stone.repeat.set(4,8);const road=texture('road');road.repeat.set(4,12);const brick=texture('brick');brick.repeat.set(2,2);
const cache=new Map();function mat(c){if(!cache.has(c))cache.set(c,new T.MeshStandardMaterial({color:c,roughness:.8}));return cache.get(c)}const masonry=new T.MeshStandardMaterial({map:brick,roughness:.93,bumpMap:brick,bumpScale:.055}),paving=new T.MeshStandardMaterial({map:stone,roughness:.95,bumpMap:stone,bumpScale:.025}),asphalt=new T.MeshStandardMaterial({map:road,roughness:.95}),glass=new T.MeshStandardMaterial({color:'#718d94',metalness:.6,roughness:.2});
const loader=new T.TextureLoader();for(const [name,material,repeat] of [['bricks',masonry,[3,3]],['paving',paving,[2,24]],['asphalt',asphalt,[3,25]]]){for(const [suffix,key] of [['color','map'],['normal','normalMap'],['rough','roughnessMap']]){loader.load(`/assets/${name}-${suffix}.jpg`,tex=>{tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.repeat.set(...repeat);tex.anisotropy=8;if(key==='map')tex.colorSpace=T.SRGBColorSpace;material[key]=tex;material.bumpMap=null;material.normalScale.set(.6,.6);material.needsUpdate=true})}}
function box(w,h,d,c,x,y,z,parent=scene){const m=new T.Mesh(new T.BoxGeometry(w,h,d),typeof c==='string'?mat(c):c);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function cyl(rt,rb,h,c,x,y,z){const m=new T.Mesh(new T.CylinderGeometry(rt,rb,h,12),mat(c));m.position.set(x,y,z);m.castShadow=true;scene.add(m);return m}
box(130,.5,130,'#727f54',0,-.65,0);box(7,.12,75,asphalt,0,-.06,0);for(const x of [-5.5,5.5]){box(4,.22,66,paving,x,0,0);box(.15,.28,66,'#c6c0af',Math.sign(x)*3.6,.03,0)}for(let z=-34;z<35;z+=5)box(.09,.015,2,'#b8b0a0',0,.014,z);for(let x=-2.8;x<3;x+=1.1)box(.65,.018,2.8,'#d5cfb9',x,.025,9);
function sign(text,parent){const c=document.createElement('canvas');c.width=1024;c.height=180;const ctx=c.getContext('2d');ctx.fillStyle='#273b36';ctx.fillRect(0,0,1024,180);ctx.strokeStyle='#ac9672';ctx.lineWidth=8;ctx.strokeRect(18,18,988,144);ctx.font='54px sans-serif';ctx.textAlign='center';ctx.fillStyle='#e4d9bc';ctx.fillText(text,512,110);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(4.6,.8),new T.MeshStandardMaterial({map:tex}));m.position.set(0,3.25,3.22);parent.add(m)}
function building(x,z,i){const g=new T.Group();g.position.set(x,0,z);g.rotation.y=x<0?Math.PI/2:-Math.PI/2;scene.add(g);const height=[7.2,6.5,8][i%3];box(7,height,6,i%2?masonry:['#c2bba8','#b0b09e','#cabca5'][i%3],0,height/2,0,g);box(7.35,.28,6.3,'#77786d',0,height+.12,0,g);box(7.15,.25,6.15,'#dfd5bf',0,3.7,0,g);box(7.2,.32,6.2,'#a29e8a',0,.25,0,g);for(const px of [-2.3,0,2.3]){box(1.85,2.4,.16,'#384d45',px,1.6,3.06,g);box(1.58,2.1,.03,glass,px,1.6,3.16,g);box(.065,2.1,.05,'#b3ad93',px,1.6,3.2,g);for(const py of [4.9,...(height>7?[6.4]:[])]){box(1.3,1.3,.16,'#e0d5be',px,py,3.05,g);box(1.09,1.1,.05,glass,px,py,3.16,g);box(1.5,.14,.4,'#d2c4a6',px,py-.7,3.2,g);box(.045,1.1,.07,'#d8cdb7',px,py,3.21,g)}}sign(['THE CORNER · 咖啡','林间书店 · BOOKS','ATELIER · 工作室','日常杂货 · MARKET'][i%4],g);box(6.6,.09,1.5,i%2?'#797d62':'#94745a',0,2.9,3.8,g).rotation.x=.12;box(.18,height+.2,.18,'#62695b',3.3,height/2,3.25,g);box(1.2,.9,1,'#91958a',2,height+.6,-1,g)}
for(let i=0;i<4;i++){building(-10,-20+i*11,i);building(10,-20+i*11,i+1)}
// Individually jointed curbs and drainage grates break up the long street surfaces.
for(let z=-31;z<33;z+=1.1)for(const side of [-1,1])box(.2,.25,1.05,'#b4b2a5',side*3.62,.01,z);
for(const z of [-17,-5,7,19])for(const side of [-1,1]){box(.45,.025,.7,'#3e4642',side*3.26,.028,z);for(let k=0;k<6;k++)box(.4,.012,.035,'#747971',side*3.26,.045,z-.28+k*.11)}
// Small architectural hardware, planters, cornices, and window reveals.
for(const x of [-6.85,6.85])for(let z=-20;z<16;z+=11){for(const dz of [-2.3,0,2.3]){box(.12,.6,.045,'#c8c3b5',x,1.45,z+dz+.35);box(.28,.07,.25,'#383e36',x,3.7,z+dz)}cyl(.34,.27,.62,'#9a7963',x, .43,z+4);for(let k=0;k<9;k++){const stem=cyl(.015,.028,.8,'#42613b',x+Math.sin(k)*.15,.94,z+4+Math.cos(k)*.15);stem.rotation.z=Math.sin(k)*.3}}
box(23,.18,9,paving,0,0,-36);box(26,1.1,.4,masonry,0,.55,-40);for(let x=-12;x<13;x+=3){box(.45,1.3,.55,'#bdb7a6',x,.65,-40);box(.65,.13,.7,'#d4ccbb',x,1.35,-40)}
const leafShape=new T.Shape();leafShape.moveTo(0,-.5);leafShape.quadraticCurveTo(.42,0,0,.5);leafShape.quadraticCurveTo(-.42,0,0,-.5);const leafGeo=new T.ShapeGeometry(leafShape,3);const leafMat=new T.MeshStandardMaterial({color:'#648044',side:T.DoubleSide,roughness:.85});const leaves=new T.InstancedMesh(leafGeo,leafMat,24000);leaves.castShadow=true;leaves.receiveShadow=true;scene.add(leaves);let leafCount=0;const dummy=new T.Object3D();
function tree(x,z,i){cyl(.075,.18,4.5,'#665442',x,2.25,z);for(let j=0;j<6;j++){const a=j*2.4;const branch=cyl(.025,.075,2,'#665442',x+Math.cos(a)*.45,3.6+rand(),z+Math.sin(a)*.45);branch.rotation.z=Math.cos(a)*.6;branch.rotation.x=Math.sin(a)*.6}for(let j=0;j<600;j++){const a=rand()*Math.PI*2,r=Math.sqrt(rand())*1.8,v=rand()*2-1;dummy.position.set(x+Math.cos(a)*r,4.7+v*1.5,z+Math.sin(a)*r);dummy.rotation.set(rand()*Math.PI,rand()*6.28,rand()*6.28);dummy.scale.setScalar(.22+rand()*.22);dummy.updateMatrix();leaves.setMatrixAt(leafCount,dummy.matrix);leaves.setColorAt(leafCount,new T.Color().setHSL(.22+rand()*.07,.28+rand()*.25,.2+rand()*.2));leafCount++}leaves.count=leafCount;leaves.instanceMatrix.needsUpdate=true;box(1.8,.16,1.8,'#777b63',x,.16,z)}
const lamps=[];for(let z=-25;z<29;z+=10)for(const side of [-1,1]){tree(side*6.5,z,Math.abs(z)%3);cyl(.055,.09,4,'#424b44',side*3.95,2,z+3);box(.6,.12,.3,'#363e37',side*3.95,4,z+3);lamps.push(box(.42,.055,.2,new T.MeshStandardMaterial({color:'#fff1c7',emissive:'#ffbd69',emissiveIntensity:.2}),side*3.95,3.92,z+3))}
for(const z of [-12,6,18])for(const side of [-1,1]){for(let k=0;k<4;k++)box(.12,.08,1.8,'#8b7051',side*6+(k-1.5)*.16,.65,z);box(.08,.55,1.8,'#8b7051',side*6.35,.93,z);for(const dz of [-.6,.6])box(.55,.6,.08,'#414e44',side*6,.33,z+dz)}
for(const z of [-6,-3]){cyl(.55,.55,.08,'#77614a',-5,1,z);cyl(.06,.08,1,'#485049',-5,.5,z);for(const dz of [-.85,.85]){cyl(.28,.28,.08,'#8e7757',-5,.55,z+dz);for(const dx of [-.18,.18])box(.04,.55,.04,'#3c4941',-5+dx,.28,z+dz)}}
for(let i=0;i<25;i++)tree((i%2?1:-1)*(18+rand()*30),-45+rand()*85,i);
const people=[],clock=new T.Clock();let paused=false,blue=false,selected=0,follow=false;const names=['阿岚','林夏','陈墨','白露','周石'];
function select(i,close=false){selected=i;const p=people[i];if(!p)return;$('resident').innerHTML=`<div class="person">${names[i]}</div><div class="job">展示居民 ${String(i+1).padStart(2,'0')} / 05</div><div class="faction">真人扫描 · 实拍皮肤和衣物</div><div class="line"><span>动作</span><span>${paused?'已暂停':p.activity}</span></div><div class="plan">使用 Renderpeople 真人扫描素材。场景共 4 套人物、5 位居民，其中两人共用同一基础素材。</div>`;if(close){follow=true;document.body.classList.add('closeup');camera.position.copy(p.model.position).add(new T.Vector3(-1.4,1.55,2.8));controls.target.copy(p.model.position).add(new T.Vector3(0,1,0))}}
$('notice').textContent='正在加载日常服装人物、环境材质和骨骼动画…';
async function loadPeople(){const gl=new GLTFLoader(),files=['nathan','sophia','manuel','rp_posed_00178_29'];const assets=await Promise.all(files.map(n=>gl.loadAsync(`/assets/scanned/${n}.glb`)));
 for(let i=0;i<5;i++){const asset=assets[i%4],visual=clone(asset.scene),model=new T.Group();model.add(visual);scene.add(model);const mixer=new T.AnimationMixer(visual);if(asset.animations.length){mixer.clipAction(asset.animations[0]).play();mixer.update(0)}visual.updateMatrixWorld(true);visual.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.update()});const bounds=new T.Box3().setFromObject(visual,true),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3());const scale=(i===1?1.68:1.78)/size.y;visual.scale.multiplyScalar(scale);visual.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);visual.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false;o.material=o.material.clone();o.material.roughness=.85}});const positions=[[4.3,.13,3],[-4.4,.13,2],[4.6,.13,-6],[-4.4,.13,-10],[4.4,.13,11]];model.position.set(...positions[i]);people.push({model,visual,mixer,offset:i*6,speed:.72+i*.055,baseY:0,activity:['散步','驻足休息','街头舞蹈','静态扫描姿势','散步'][i]})}select(0);$('notice').textContent='真人扫描人物已就绪 · 点击人物查看皮肤与衣物细节';window.__townReady=true}
loadPeople().catch(error=>{$('notice').textContent='人物加载失败，请刷新检查资源连接';console.error(error)});
function overview(){follow=false;document.body.classList.remove('closeup');camera.position.set(2,13,28);controls.target.set(0,1,-2)}function street(){follow=false;document.body.classList.remove('closeup');camera.position.set(-2,2.1,17);controls.target.set(-1,1.6,-8)}
$('settings').onclick=()=>select(selected,true);$('reset').onclick=overview;$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'继续行走':'暂停行走';select(selected)};$('night').onclick=()=>{blue=!blue;scene.fog.color.set(blue?'#768b9e':'#c6d1cf');sun.intensity=blue?.35:3.8;sun.color.set(blue?'#94b5e0':'#ffe0ad');hemi.intensity=blue?.8:1.5;renderer.toneMappingExposure=blue?.75:1.05;sky.material.uniforms.sunPosition.value.set(-18,blue?-2:25,12);lamps.forEach(l=>l.material.emissiveIntensity=blue?4:.2);$('night').textContent=blue?'黄金时刻':'蓝调时刻'};
addEventListener('keydown',e=>{if(e.key==='1')overview();if(e.key==='2')street();if(e.key==='3')select(selected,true);if(e.key.toLowerCase()==='h')document.body.classList.toggle('hide-ui')});controls.addEventListener('start',()=>follow=false);
let down;const ray=new T.Raycaster();renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);const hits=ray.intersectObjects(people.map(p=>p.model),true);if(hits.length){let o=hits[0].object;while(o&&!people.some(p=>p.model===o))o=o.parent;const i=people.findIndex(p=>p.model===o);if(i>=0)select(i,true)}});
let elapsed=0;renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(!paused&&!document.hidden)elapsed+=dt;people.forEach(p=>{if(!paused&&!document.hidden)p.mixer.update(dt)});if(follow&&people[selected]){const target=people[selected].model.position.clone().add(new T.Vector3(0,1,0));camera.position.add(target.clone().sub(controls.target));controls.target.copy(target)}controls.update();renderer.render(scene,camera)});
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();street();window.__town={people,renderer,scene,camera,select,street,overview,measure:()=>people.map(p=>{const b=new T.Box3().setFromObject(p.visual,true);return {size:b.getSize(new T.Vector3()).toArray(),center:b.getCenter(new T.Vector3()).toArray(),feet:b.min.y}})};
