import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import {clone} from 'three/addons/utils/SkeletonUtils.js';
import {Sky} from 'three/addons/objects/Sky.js';
import {buildTerrain} from './original-terrain.js';
import './world-ui.css';
import './live-world.css';
import {connectWorld} from './live-world.js';
import {createLife} from './resident-life.js';
import {boneKey} from './retarget-cast.js';
const cast={乐乐:'nathan',鲍勃:'manuel',斯黛拉:'carla',爱丽丝:'claudia',皮特:'eric',林岚:'Female_Adult_01',周石:'Male_Adult_08',苏菲:'sophia'};

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
document.body.innerHTML=`<canvas id="world" aria-label="原 AI 小镇三维场景"></canvas>
<header><div class="brand">◈ <b>原野小镇</b><span>原世界 · 第三维</span></div><div class="state"><i></i>本地规则活动 · LLM 未连接</div><button id="overview">全镇鸟瞰</button></header>
<section class="summary"><small>THE SAME WORLD, ANOTHER DIMENSION</small><h1>回到熟悉的小镇。</h1><p id="summary-info">正在读取原世界…</p><div id="statistics"></div></section>
<aside><div class="panel-heading">原居民档案 <span id="resident-count"></span></div><label class="select-label">选择居民<select id="resident-select"></select></label><section id="profile"></section></aside>
<section class="map-panel"><div class="panel-heading">原图定位 <button id="compare">查看原图 ↗</button></div><div class="mini-wrap"><img id="mini" src="/world/original-map.png" alt="来自原存档的64乘48地图"><div id="map-pins"></div></div><p>标记显示当前展示位置 · 原坐标保留在档案</p></section>
<footer><span>拖动旋转 · 滚轮缩放 · 点击居民 · H 隐藏界面</span><nav><button id="closeup">人物近景</button><button id="next">下一位</button><button id="ambient">暂停环境动画</button><button id="poses">暂停画面动作</button><button id="lighting">傍晚光照</button></nav></footer>
<div id="notice" role="status">正在重建原来的 64×48 地图…</div>
<dialog id="map-dialog"><div class="dialog-heading"><h2>原世界地图对照</h2><button id="close-map">关闭</button></div><p>原地图的图块和碰撞层完整保留；主场景按同一坐标搭建写实地形。风车和营火在原图中用框标注。</p><img src="/world/original-map.png" alt="原64乘48地图全图"><div id="audit"></div></dialog>`;

const scene=new T.Scene();scene.background=new T.Color('#c9d8dd');scene.fog=new T.Fog('#c9d8dd',180,350);
const renderer=new T.WebGLRenderer({canvas:$('world'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;
const camera=new T.PerspectiveCamera(43,innerWidth/innerHeight,.1,350);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=2;controls.maxDistance=170;controls.maxPolarAngle=Math.PI*.49;
const sun=new T.DirectionalLight('#ffecd2',2.5);sun.position.set(-35,65,28);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:55,bottom:-55,near:1,far:150});sun.shadow.normalBias=.035;scene.add(sun);const hemi=new T.HemisphereLight('#cfe5ff','#778466',1.65);scene.add(hemi);
const sky=new Sky();sky.scale.setScalar(240);sky.material.uniforms.turbidity.value=3;sky.material.uniforms.rayleigh.value=1.3;sky.material.uniforms.sunPosition.value.copy(sun.position);scene.add(sky);
new RGBELoader().load('/assets/sunset.hdr',t=>{t.mapping=T.EquirectangularReflectionMapping;scene.environment=t;scene.environmentIntensity=.55});
let live,life,data,terrain,people=[],selected=0,environmentPlaying=true,posesPlaying=true,time=0,evening=false;
function overview(){camera.position.set(62,98,110);controls.target.set(0,0,0);people.forEach(p=>p.tag.visible=true);document.body.classList.remove('portrait')}
overview();
function nametag(name,color){const c=document.createElement('canvas');c.width=384;c.height=100;const ctx=c.getContext('2d');ctx.fillStyle='#f9fcf0e8';ctx.beginPath();ctx.roundRect(8,8,368,84,24);ctx.fill();ctx.fillStyle=color;ctx.font='bold 42px sans-serif';ctx.textAlign='center';ctx.fillText(name,192,66);const tex=new T.CanvasTexture(c),tag=new T.Sprite(new T.SpriteMaterial({map:tex,depthTest:false}));tag.scale.set(1.75,.46,1);return tag}
function renderProfile(resident){const i=Number(resident.character.slice(1))-1,portraitX=-(i%4)*96,portraitY=-Math.floor(i/4)*128,partner=data.residents.find(r=>r.playerId===resident.partnerId);const relationships=data.relationships.filter(r=>r.player1===resident.playerId||r.player2===resident.playerId).slice(0,5);const relationHtml=relationships.map(r=>{const other=data.residents.find(p=>p.playerId===(r.player1===resident.playerId?r.player2:r.player1));return `<div class="rel"><b>${esc(other?.name)}</b><span>${esc(r.stage)} · 信任 ${esc(r.trust)}</span></div>`}).join('');
 $('profile').innerHTML=`<div class="identity"><div class="original-avatar" title="原版形象 ${esc(resident.character)}" style="background-position:${portraitX}px ${portraitY}px"></div><div><h2>${esc(resident.name)}</h2><p>${esc(resident.job)}</p></div></div><div class="tags"><span>${esc(resident.faction)}</span><span>${resident.alive?'在世':'已故'}</span></div><div class="metric"><span>生命值</span><b>${esc(resident.health)} / 100</b></div><div class="health"><i style="width:${Math.max(0,Math.min(100,resident.health))}%;background:${resident.health<35?'#c57959':'#87a570'}"></i></div><div class="metric"><span>当前展示动作</span><b id="live-activity">驻足休息</b></div><div class="metric"><span>原地图坐标</span><b>${resident.position.x.toFixed(2)}, ${resident.position.y.toFixed(2)}</b></div><div class="metric"><span>金币 / 声望</span><b>${esc(resident.coins)} / ${esc(resident.reputation)}</b></div><div class="metric"><span>工作地点</span><b>${esc(resident.workplace)}</b></div><div class="metric"><span>伴侣</span><b>${esc(partner?.name??'无')}</b></div><div class="metric"><span>长期记忆 / 反思</span><b>${resident.memories.count} / ${resident.memories.reflections}</b></div><details open><summary>身份与性格 · 原资料</summary><p>${esc(resident.identity)}</p></details><details><summary>长期目标与当前计划</summary><p>${esc(resident.longTermPlan)}</p><p>${esc(resident.currentPlan)}</p>${resident.dailyPlan.map(p=>`<p><b>${esc(p.period)}</b> ${esc(p.activity)} · ${esc(p.location)}</p>`).join('')}</details><details><summary>关系与家庭</summary>${relationHtml}<p>${esc(resident.householdId??'尚未建立家庭')}</p></details><details><summary>最近的记忆 · 存档摘录</summary>${resident.memories.recent.map(m=>`<p>${esc(m.description)}</p>`).join('')||'<p>暂无记忆</p>'}</details><details><summary>物品与价值观</summary><p>${resident.inventory.map(i=>`${esc(i.item)} × ${esc(i.quantity)}`).join('、')}</p><p>${resident.values.map(esc).join(' / ')}</p></details><div class="source-note">姓名、资料、状态与坐标来自同一份暂停存档。每人使用独立人物模型，保持原居民身份；本地活动不写回存档。</div>`;
 $('resident-select').value=resident.playerId;document.querySelectorAll('.map-pin').forEach(b=>b.classList.toggle('selected',b.dataset.id===resident.playerId));
}
function select(index,close=false){selected=index;const p=people[index];if(!p)return;renderProfile(p.resident);people.forEach((r,i)=>{r.tag.visible=!close;r.tag.material.opacity=i===index?1:.75});if(close){const target=p.group.position.clone().add(new T.Vector3(0,1,0));camera.position.copy(target).add(new T.Vector3(1.7,.5,3.2));controls.target.copy(target);document.body.classList.add('portrait')}}
async function load(){const res=await fetch('/world/snapshot.json');if(!res.ok)throw Error('无法读取原世界快照');data=await res.json();terrain=await buildTerrain(scene,data.map,renderer);const residents=data.residents.filter(r=>r.alive);$('summary-info').textContent='原树林、河流、营地和风车，沿用原坐标。';$('statistics').innerHTML=`<div><b>${data.provenance.day}</b><span>存档日</span></div><div><b>${residents.length}</b><span>原居民</span></div><div><b>64×48</b><span>原地图</span></div>`;$('resident-count').textContent=`${residents.length} / ${data.residents.length}`;$('resident-select').innerHTML=residents.map(r=>`<option value="${esc(r.playerId)}">${esc(r.name)} · ${esc(r.job)}</option>`).join('');
 const loader=new GLTFLoader(),files=[...new Set(residents.map(r=>cast[r.name]))],assets=new Map(await Promise.all(files.map(async n=>[n,await loader.loadAsync(`/assets/scanned/${n}.glb`)])));
 for(const resident of residents){const asset=assets.get(cast[resident.name]),visual=clone(asset.scene),group=new T.Group();group.add(visual);const bindPose=new Map();visual.traverse(o=>{if(o.isBone)bindPose.set(o.name,{position:o.position.clone(),quaternion:o.quaternion.clone(),scale:o.scale.clone()})});const mixer=new T.AnimationMixer(visual);if(asset.animations.length){mixer.clipAction(asset.animations[0]).play();mixer.update(.05)}visual.updateMatrixWorld(true);visual.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.update()});const bounds=new T.Box3().setFromObject(visual,true),center=bounds.getCenter(new T.Vector3()),height=bounds.max.y-bounds.min.y,scale=(['carla','claudia','sophia','Female_Adult_01'].includes(cast[resident.name])?1.67:1.78)/height;visual.scale.multiplyScalar(scale);visual.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);visual.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false;o.material=o.material.clone();o.material.roughness=.85}});const[x,z]=terrain.xy(resident.position.x,resident.position.y);group.position.set(x,terrain.height(resident.position.x,resident.position.y)+.03,z);group.rotation.y=Math.atan2(resident.facing.dx,resident.facing.dy);scene.add(group);group.updateMatrixWorld(true);let hip;visual.traverse(o=>{if(o.isBone&&boneKey(o.name)==='hip')hip=o});const hipAnchor=hip?group.worldToLocal(hip.getWorldPosition(new T.Vector3())):null;const tag=nametag(resident.name,resident.faction==='公共协作派'?'#557c8c':'#8b764e');tag.position.copy(group.position).add(new T.Vector3(0,2.05,0));scene.add(tag);people.push({bindPose,assetId:cast[resident.name],resident,group,model:group,visual,mixer,tag,hip,hipAnchor});const pin=document.createElement('button');pin.className='map-pin';pin.dataset.id=resident.playerId;pin.title=`${resident.name} (${resident.position.x.toFixed(1)}, ${resident.position.y.toFixed(1)})`;pin.style.left=`${resident.position.x/data.map.width*100}%`;pin.style.top=`${resident.position.y/data.map.height*100}%`;pin.textContent=resident.name[0];const index=people.length-1;pin.onclick=()=>select(index,true);$('map-pins').append(pin)}
 life=createLife(people,assets,terrain,data.map);
 select(0);$('notice').textContent=`原世界第 ${data.provenance.day} 天 · ${people.length} 位居民 · 本地活动展示，不写入原存档`;$('audit').textContent=`原地图 ${data.map.width}×${data.map.height} · ${data.map.bgTiles.length} 个背景层 · ${data.map.objectTiles.length} 个碰撞层 · ${data.map.props.length} 个物品/地标映射 · 存档代数 ${data.provenance.generation}`;window.__townReady=true;window.__town={people,renderer,scene,camera,select,overview,data,terrain,life,refreshProfile:()=>renderProfile(people[selected].resident),measure:()=>people.map(p=>{const b=new T.Box3().setFromObject(p.visual,true);return {name:p.resident.name,id:p.resident.playerId,sourcePosition:p.resident.position,position:p.group.position.toArray(),size:b.getSize(new T.Vector3()).toArray()}})};
}
load().then(()=>{life.pauseLive();live=connectWorld(window.__town);window.__town.live=live}).catch(e=>{$('notice').textContent='载入失败：'+e.message;console.error(e)});
$('resident-select').onchange=e=>select(people.findIndex(p=>p.resident.playerId===e.target.value),true);$('overview').onclick=overview;$('closeup').onclick=()=>select(selected,true);$('next').onclick=()=>select((selected+1)%people.length,true);$('ambient').onclick=()=>{environmentPlaying=!environmentPlaying;$('ambient').textContent=environmentPlaying?'暂停环境动画':'继续环境动画'};$('poses').onclick=()=>{posesPlaying=!posesPlaying;$('poses').textContent=posesPlaying?'暂停居民活动':'继续画面动作'};$('compare').onclick=()=>$('map-dialog').showModal();$('close-map').onclick=()=>$('map-dialog').close();$('lighting').onclick=()=>{evening=!evening;sun.color.set(evening?'#ffb778':'#ffecd2');sun.intensity=evening?1.4:2.5;sun.position.set(-35,evening?22:65,28);sky.material.uniforms.sunPosition.value.copy(sun.position);$('lighting').textContent=evening?'日间光照':'傍晚光照'};
addEventListener('keydown',e=>{if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key.toLowerCase()==='h')document.body.classList.toggle('hide-ui');if(e.key==='1')overview();if(e.key==='3')select(selected,true)});
const ray=new T.Raycaster();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);const hits=ray.intersectObjects(people.flatMap(p=>[p.group,p.tag]),true);if(!hits.length){const plane=new T.Plane(new T.Vector3(0,1,0),0),point=new T.Vector3();if(ray.ray.intersectPlane(plane,point)){const destination=life.worldToTile(point);void live?.move(destination)}return;}let object=hits[0].object;let index=-1;while(object&&index<0){index=people.findIndex(p=>p.group===object||p.tag===object);object=object.parent}if(index>=0)select(index,true)});
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);const previous=people[selected]?.group.position.clone();if(!document.hidden){if(environmentPlaying){time+=dt;terrain?.update(time)}if(posesPlaying)life?.step(dt)}if(document.body.classList.contains('portrait')&&previous){const delta=people[selected].group.position.clone().sub(previous);camera.position.add(delta);controls.target.add(delta)}const status=document.getElementById('live-activity');if(status&&people[selected])status.textContent=posesPlaying?people[selected].status:'活动已暂停';controls.update();terrain?.updateView(camera,performance.now()/1000);renderer.render(scene,camera)});
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
